import java.net.URI

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */

allprojects {
    repositories {
        jcenter()
        mavenCentral()
        maven { url = URI("https://repo.spring.io/milestone") }
    }
}

subprojects {
    version = "1.0"
}