import java.net.URI

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */

allprojects {
    repositories {
        jcenter()
        mavenCentral()
        maven { url = URI("https://repo.spring.io/milestone") }
    }
}

subprojects {
    version = "1.0"

    buildscript {
        val kotlinVersion = "1.3.0"
        val springBootVersion = "2.1.0.RELEASE"

        repositories {
            mavenCentral()
        }
        dependencies {
            classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
            classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:${kotlinVersion}")
            classpath("org.jetbrains.kotlin:kotlin-allopen:${kotlinVersion}")
        }
    }

    apply(plugin = "java-library")
    apply(plugin = "java")
    apply(plugin = "idea")
}