spring:
  application:
    name: GameService

server:
  port: 8091

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.int}}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
