spring:
  application:
    name: GameService

server:
  port: 8090

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.int(0,1000000000)}}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
