server:
  port: 8081


spring:
  application:
    name: kotlingirl-matchmaker

eureka:
  client:
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

ping-server:
  ribbon:
    eureka:
      enabled: false # do not confirm with eureka

