spring:
  application:
    name: kotlingirl-gameservice

server:
  port: 8091

eureka:
#  instance:
#    instanceId: ${spring.application.instance_id:${random.value}}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
